### ISSUE TITLE
Child Process Spawnen funktioniert nicht

### ISSUE THREAD

**Issue by roehlc** [ewsnaj/gesten#3]
root@kali:~/Downloads/gesten-master# nodejs app.js 
/root/Downloads/gesten-master/app.js:390
  var { spawn } = require('child_process');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

**Comment by picsel2** [comment]
Klappt es, nachdem du die Abhängigkeiten installiert hast?

**Comment by roehlc** [comment]
kann ich nciht sagen, weil npm install nicht funktioniert:

root@kali:~/Downloads/gesten-master# npm install
bash: npm: command not found

muss man npm erst noch installieren?

**Comment by ewsnaj** [comment]
> muss man npm erst noch installieren?
Ja , wenns nicht automatisch bei der installation von node passiert

**Comment by roehlc** [comment]
node ist wohl standardmäßig unter kali installiert. aber npm anscheinend nicht.

**Comment by roehlc** [comment]
jetzt geht es
