### ISSUE TITLE
Module is-root kann nicht gefunden werden

### ISSUE THREAD

**Issue by roehlc** [ewsnaj/gesten#4]
Meine Umgebung: Kali installiert, EyeWitness gedownloaded und in $PATH eingetragen, den masterbranch von github als zip gedaownloaded und dann entpackt. Dann habe ich mal die Zeilen zum spawnen des Firefox Prozesses auskommentiert (das hat ja wie in #3 beschrieben auch Probleme gemacht). Und unsere Anwendung mit "nodejs app.js" gestartet.

Jetzt stört der sich nicht mehr an Firefox aber dafür bekomme ich diese Fehlermeldung:

root@kali:~/Downloads/gesten-master# nodejs app.js 
module.js:327
    throw err;
    ^

Error: Cannot find module 'is-root'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/Downloads/gesten-master/app.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by roehlc** [comment]
vermute mal das kann man mit "npm install --save is-root" lösen?

**Comment by picsel2** [comment]
Das klingt sehr nach fehlenden Abhängigkeiten.

**Comment by picsel2** [comment]
Das Paket is-root ist als Abhängigkeit in der package.json enthalten, also müsste ein `npm install` reichen.
